### ISSUE TITLE
Deprecated while running DB query in Tinker

### ISSUE THREAD

**Issue by TiiFuchs** [spatie/laravel-ray#239]
**Describe the bug**
Running `ray()->showQueries()` in Artisan Tinker and executing a database query afterwards, results in a 

```
PHP Deprecated:  str_starts_with(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 845
PHP Deprecated:  str_starts_with(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 845
PHP Deprecated:  str_starts_with(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 845
```

That's the stacktrace:
```
#0 /var/www/html/vendor/spatie/laravel-ray/src/OriginFactory.php(136): Illuminate\Support\Str::startsWith(NULL, '...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(1037): Spatie\LaravelRay\OriginFactory->Spatie\LaravelRay\{closure}(Object(Spatie\Backtrace\Frame), 48)
#2 /var/www/html/vendor/spatie/laravel-ray/src/OriginFactory.php(137): Illuminate\Support\Collection->search(Object(Closure))
#3 /var/www/html/vendor/spatie/laravel-ray/src/OriginFactory.php(84): Spatie\LaravelRay\OriginFactory->findFrameForQuery(Object(Illuminate\Support\Collection))
#4 /var/www/html/vendor/spatie/laravel-ray/src/OriginFactory.php(28): Spatie\LaravelRay\OriginFactory->getFrame()
#5 /var/www/html/vendor/spatie/ray/src/Payloads/Payload.php(56): Spatie\LaravelRay\OriginFactory->getOrigin()
#6 /var/www/html/vendor/spatie/ray/src/Payloads/Payload.php(42): Spatie\Ray\Payloads\Payload->getOrigin()
#7 /var/www/html/vendor/spatie/ray/src/Request.php(30): Spatie\Ray\Payloads\Payload->toArray()
#8 [internal function]: Spatie\Ray\Request->Spatie\Ray\{closure}(Object(Spatie\LaravelRay\Payloads\ExecutedQueryPayload))
#9 /var/www/html/vendor/spatie/ray/src/Request.php(31): array_map(Object(Closure), Array)
#10 /var/www/html/vendor/spatie/ray/src/Request.php(42): Spatie\Ray\Request->toArray()
#11 /var/www/html/vendor/spatie/ray/src/Client.php(75): Spatie\Ray\Request->toJson()
#12 /var/www/html/vendor/spatie/ray/src/Ray.php(760): Spatie\Ray\Client->send(Object(Spatie\Ray\Request))
#13 /var/www/html/vendor/spatie/laravel-ray/src/Ray.php(507): Spatie\Ray\Ray->sendRequest(Array, Array)
#14 /var/www/html/vendor/spatie/laravel-ray/src/Watchers/QueryWatcher.php(43): Spatie\LaravelRay\Ray->sendRequest(Object(Spatie\LaravelRay\Payloads\ExecutedQueryPayload))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Spatie\LaravelRay\Watchers\QueryWatcher->Spatie\LaravelRay\Watchers\{closure}(Object(Illuminate\Database\Events\QueryExecuted))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('...', Array)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(885): Illuminate\Events\Dispatcher->dispatch('...')
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(728): Illuminate\Database\Connection->event(Object(Illuminate\Database\Events\QueryExecuted))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(683): Illuminate\Database\Connection->logQuery('...', Array, 187.57)
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run('...', Array, Object(Closure))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2484): Illuminate\Database\Connection->select('...', Array, true)
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2472): Illuminate\Database\Query\Builder->runSelect()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3006): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2473): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(632): Illuminate\Database\Query\Builder->get(Array)
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(616): Illuminate\Database\Eloquent\Builder->getModels(Array)
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->get()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2131): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), '...', Array)
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2143): Illuminate\Database\Eloquent\Model->__call('...', Array)
#30 /var/www/scratches/scratch.php(5): Illuminate\Database\Eloquent\Model::__callStatic('...', Array)
#31 /var/www/html/vendor/psy/psysh/src/Shell.php(459): include_once('...')
#32 /var/www/html/vendor/psy/psysh/src/Shell.php(476): Psy\Shell->Psy\{closure}(Object(Psy\Shell))
#33 /var/www/html/vendor/psy/psysh/src/Shell.php(379): Psy\Shell->loadIncludes()
#34 /var/www/html/vendor/psy/psysh/src/Shell.php(352): Psy\Shell->doInteractiveRun()
#35 /var/www/html/vendor/symfony/console/Application.php(171): Psy\Shell->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Psy\Output\ShellOutput))
#36 /var/www/html/vendor/psy/psysh/src/Shell.php(327): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Psy\Output\ShellOutput))
#37 /var/www/html/vendor/laravel/tinker/src/Console/TinkerCommand.php(81): Psy\Shell->run()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Tinker\Console\TinkerCommand->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#44 /var/www/html/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#46 /var/www/html/vendor/symfony/console/Application.php(989): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Tinker\Console\TinkerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#51 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Versions**
Ray version: 1.19.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.33.2
- spatie/laravel-ray package version (if applicable): 1.29.1

PHP version: 8.1.2
Laravel version: 9.0.2

**To Reproduce**
1. Execute `php artisan tinker`
2. Enter `ray()->showQueries()`
3. Fetch a Eloquent Model from the database or do something else that executes a query.

**Expected behavior**
There should not be a Deprecated Message

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.1

**Comment by freekmurze** [comment]
We'll handle this in #240
